### ISSUE TITLE
Rendering from orthographic projection gives wrong ordering

### ISSUE THREAD

**Issue by Fuzzillogic** [Nutek/blender_export_svg#4]
STR:

- Blender 3.6.2
- From default scene, create copies of the cube, place them above, next to and behind the default cube.
- Switch to orthographic view. (Numpad 5)
- Select the four cubes for export:
   ![image](https://github.com/Nutek/blender_export_svg/assets/10601512/235c8787-5191-428f-9632-b47e85331622)
- In SVG Export options, disable "Facing only", for extra effect.
- Export SVG.

Expected:
![image](https://github.com/Nutek/blender_export_svg/assets/10601512/905d7fb3-6174-4526-a53a-a059a529b781)

Actual:
![image](https://github.com/Nutek/blender_export_svg/assets/10601512/5fa0cf9a-7918-4a71-baa9-d42f96f82e48)

As you might have guessed, I think I found the problem and managed to fix it. The script does two things for orthographic view which seem wrong, or at least no longer needed:
1. Simply remove [Line 75, dot = -dot](https://github.com/Nutek/blender_export_svg/blob/44446682c71c2c4d930881016b9798a6bc394e2e/export_svg_280.py#L75). At least I don't understand why the dot product should be inverted here.
2. The [if in Line 351 and 352](https://github.com/Nutek/blender_export_svg/blob/44446682c71c2c4d930881016b9798a6bc394e2e/export_svg_280.py#L351) sorts depending on orthographic view. Again, I don't understand why that's needed. When the condition is removed, and `distancia.sort(reverse=True)` is used regardless whether in orthographic view or not, it works fine.

With these two modifications in place, then I get the "expected" result pictured above. So at least it seems better, but there might be other problems lurking. And as said, I simply don't know what these two pieces of code were meant to do in the first place.

**Comment by Nutek** [comment]
Nice catch. I'll introduce those changes and try to play around them. I hope I'll catch some regressions when they appear.

I plan to change structure of this script a bit to provide more options about ordering. For now it is difficult what will happen if  you try to `order objects` and use `connect objects` option. Work in progress. ;)

**Comment by Nutek** [comment]
I'm not pretty sure yet what dot product is returned for in this place. The most significant change was to sort in the same way regardless to kind of perspective.

I will play a bit more to test different scenarios and then I merge changes.
