### ISSUE TITLE
Missing faces when creating SVG

### ISSUE THREAD

**Issue by nurdism** [Nutek/blender_export_svg#9]
Any help would be much apricated!

I have this object: 
![img](https://i.imgur.com/sv1dFna.png)

It renders this svg:
![img](https://i.imgur.com/Q5U2uTj.png)

As you can see, its missing some of the faces on the RS text, I've tried a bunch of settings and I cant seem to get the faces to show up. These are the settings I'm using:
![img](https://i.imgur.com/KzwMyLF.png)

I'm attaching the blender file and the generated svg:
[algo.svg](https://github.com/Nutek/blender_export_svg/assets/420102/3976f572-86c7-4650-86b7-a7f3390f541c)
[error.blend](https://github.com/Nutek/blender_export_svg/files/13807329/blend.zip)

I'm using blender 4.0.2

**Comment by Nutek** [comment]
I've downloaded file and looked into model.

Regarding to my knowledge this plugin should be able to handle this model and present all faces visible on view in blender.

I'll mark this topic as BUG.

**Comment by Nutek** [comment]
Hi @nurdism 

I've played with your file a bit and I found solution how to generate your file in proper way.

At first there is still issue with managing state of parameters. In particular with those which are not changed from default state yet.

My result from settings:
![obraz](https://github.com/Nutek/blender_export_svg/assets/4632700/75349805-ac96-480c-9e02-d3c10aac247e)

is like below:
![obraz](https://github.com/Nutek/blender_export_svg/assets/4632700/75435d8d-5537-4c1e-9dfd-f5149046f449)

How to workaround issues?

1. Change each parameter to desired value
2. If desired value is same like default one then change to different one and back to default one.
3. If there is issue with missing faces it used to be section with collapsing or dissolving edges.
![obraz](https://github.com/Nutek/blender_export_svg/assets/4632700/722c735c-4ef0-4b87-b704-0837d1ddfbed)
4. Default values may not be the same like displayed default values. Please try play around those parameters. It might help.

In case of further issues or questions please let me know.

Is that explanation solves your issue? (At least for now)

**Comment by nurdism** [comment]
That works thanks for the workaround, I see that it's an issue with the state of the parameters.
